### ISSUE TITLE
Error loading mods  config.engine.on is not a function

### ISSUE THREAD

**Issue by ArronHoltzhausen** [screeps/launcher#2] opened 2016-11-19 01:52 UTC
Loading mods from "/opt/mods.json"
 - /opt/mods/welcome-text.js
 - /opt/mods/tick-duration.js
 - /opt/mods/change-constant.js
 - /opt/mods/cli-method.js
 - /opt/mods/cronjob.js
 - /opt/mods/driver-method.js
 - /opt/mods/http-endpoint.js
 - /opt/mods/notifications-mailer/notifications-mailer.js
Error loading "/opt/mods/player-sandbox.js": TypeError: config.engine.on is not a function
    at module.exports (/opt/mods/player-sandbox.js:5:23)
    at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
    at Array.forEach (native)
    at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
    at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
Error loading "/opt/mods/process-object.js": TypeError: config.engine.on is not a function
    at module.exports (/opt/mods/process-object.js:5:23)
    at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
    at Array.forEach (native)
    at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
    at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
Error loading "/opt/mods/room-history.js": TypeError: config.engine.on is not a function
    at module.exports (/opt/mods/room-history.js:13:23)
    at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
    at Array.forEach (native)
    at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
    at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
 - /opt/mods/custom-objects/simple.js
Error loading "/opt/mods/custom-objects/advanced.js": TypeError: config.engine.on is not a function
    at module.exports (/opt/mods/custom-objects/advanced.js:34:23)
    at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
    at Array.forEach (native)
    at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
    at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

**Comment by artch** [comment] 2016-11-20 07:55
What is server version?

**Comment by artch** [comment] 2016-11-20 07:56
Duplicate of https://github.com/screeps/screeps/issues/21

**Closed by artch** 2016-11-20 07:56 UTC
